name: Nook CI

on:
  pull_request:
    branches: [ master ]
    paths:
    - 'webapp/**'

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: google/dart:2.10.4

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts
        echo fingerprint
        ssh-keygen -lf ~/.ssh/known_hosts
        echo ssh test
        ssh -o UserKnownHostsFile=~/.ssh/known_hosts -T git@github.com
        mkdir -p ~/.pub-cache
        echo git clone test
        git clone --mirror git@github.com:larksystems/katikati_ui_lib.dart.git /github/home/.pub-cache/git/cache/katikati_ui_lib.dart-3bb29a7278798a4357cb8d178854b7206d1897e5
    - name: Build Release
      run: |
        cd webapp
        pub global activate webdev
        export PATH="$PATH":"$HOME/.pub-cache/bin"
        webdev build
