name: Nook CI

on:
  pull_request:
    branches: [ master ]
    paths:
    - 'webapp/**'

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: google/dart:2.10.4

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo ls -alF /root/.ssh
        sudo cat /etc/ssh/ssh_config

        echo known hosts
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts
        echo fingerprint 1
        ssh-keygen -lf ~/.ssh/known_hosts

        echo ssh test
        set +e
        #ssh -o UserKnownHostsFile=~/.ssh/known_hosts -o StrictHostKeyChecking=no -T git@github.com
        ssh -vvvvvvvvvvvvv -o UserKnownHostsFile=~/.ssh/known_hosts -T git@github.com
        set -e
        cat ~/.ssh/known_hosts
        echo fingerprint 2
        ssh-keygen -lf ~/.ssh/known_hosts

        echo git clone test
        mkdir -p ~/.pub-cache
        git clone --mirror git@github.com:larksystems/katikati_ui_lib.dart.git /github/home/.pub-cache/git/cache/katikati_ui_lib.dart-3bb29a7278798a4357cb8d178854b7206d1897e5
    - name: Build Release
      run: |
        cd webapp
        pub global activate webdev
        export PATH="$PATH":"$HOME/.pub-cache/bin"
        webdev build
